export declare const date: string;
export declare const daysList: string;
export declare const employeeCard: string;
export declare const error: string;
export declare const loadingOverlay: string;
export declare const noData: string;
export declare const resultContainer: string;
export declare const time: string;
export declare const wrapper: string;
